CREATE DATABASE splitwise;

\c splitwise

CREATE TABLE users (
    id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username        varchar(80) NOT NULL CHECK(username <> '')
);

CREATE TABLE transactions (
    id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id         integer REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    amount          integer CHECK (amount > 0) NOT NULL,
    timestamp       timestamptz NOT NULL,
    vendor          varchar(80) CHECK(vendor <> '') NOT NULL,
    description     varchar(300),
    split_with      integer REFERENCES users (id) ON DELETE CASCADE NOT NULL
);